### ISSUE TITLE
Small visual bug - not too bad though

### ISSUE THREAD

**Issue by chandraskappagantula** [Scratle/fiddlings#1]
![image](https://user-images.githubusercontent.com/85963035/122604079-387f4200-d02a-11eb-8254-b52ef6047230.png)

Slight orange showing out, but don't know if it's intended.

**Comment by Scratle** [comment]
That's intended.. Check out what happens when you do a few more reviews ;) (Oleg's idea)

**Comment by Oaphi** [comment]
Huh, that's the perfect time to say "it's not a bug, it's a feature!"
